[build]
command = "npm run build"
publish = "public"

[build.environment]
NODE_VERSION = "22"

[build.processing]
skip_processing = false

[build.processing.html]
pretty_urls = true

[build.processing.css]
bundle = true
minify = true

[build.processing.js]
bundle = true
minify = true

[build.processing.images]
compress = true

# Redirecciones HTTP a HTTPS
[[redirects]]
  from = "http://centredentalbaste.com/*"
  to = "https://centredentalbaste.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://www.centredentalbaste.com/*"
  to = "https://centredentalbaste.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://www.centredentalbaste.com/*"
  to = "https://centredentalbaste.com/:splat"
  status = 301
  force = true

# Redirección del archivo de verificación de Google
[[redirects]]
  from = "/google5f3d2fed92020926/"
  to = "/google5f3d2fed92020926.html"
  status = 301